
export default function AboutUs() {
 
  return (
    <div>
        <b className="header-level1">About Recipe App</b>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel elit sem. Maecenas in lacus in ex porttitor tempus. Praesent sodales magna ac quam commodo, quis pretium erat hendrerit. Fusce vel orci tellus. Nunc sit amet sodales leo. Duis at quam sed felis placerat mollis. Praesent malesuada viverra malesuada. Pellentesque id arcu orci. Mauris ornare volutpat elit, eu ultrices lectus pharetra a. Morbi cursus at tortor mattis fringilla. Aliquam erat volutpat. Duis mollis viverra orci, vel maximus diam tincidunt sed. Vestibulum dui velit, rutrum id dolor a, ultrices ornare eros.</p>
        <p>Mauris metus quam, elementum nec vulputate cursus, feugiat nec nibh. Maecenas tempor mollis metus, a efficitur felis iaculis in. Suspendisse porttitor nunc ornare feugiat laoreet. Curabitur fringilla libero interdum lectus rhoncus efficitur. Pellentesque ut tempor velit, eget tristique est. Suspendisse potenti. Donec enim felis, rutrum at tempor sed, lacinia id quam. Sed ipsum ligula, lobortis vitae volutpat ut, rhoncus sed dolor.</p>
        <p>In vitae lorem odio. Nullam efficitur bibendum ultrices. Nam scelerisque odio ac nibh sodales, eget mollis lacus tincidunt. Integer tincidunt dictum libero vitae accumsan. Fusce leo turpis, vehicula nec interdum quis, dictum at enim. Praesent ante elit, vehicula at ante eu, consequat auctor sapien. Mauris vel auctor ex, eu volutpat magna. Sed auctor lorem nisl, a suscipit urna viverra ac. Maecenas lectus elit, dapibus non nunc vel, cursus vulputate eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque risus id lacus mollis mattis. Phasellus ornare velit tortor, ut consectetur purus maximus in. Nulla consectetur blandit lacus, sit amet volutpat nulla pharetra a. Quisque sed mi faucibus, feugiat magna feugiat, suscipit elit.</p>
        <p>Phasellus arcu ex, maximus eu rutrum a, pharetra a enim. Etiam gravida venenatis justo. Aenean consectetur ex nisl, feugiat porta tortor auctor eget. Maecenas arcu ipsum, posuere ac elementum vitae, dignissim sit amet diam. Fusce vitae rhoncus lacus. Proin tortor quam, fringilla in erat ac, mollis malesuada lorem. Integer dictum ligula quis dui consectetur feugiat. Maecenas tincidunt mattis dui, placerat fringilla dui malesuada vitae. Duis molestie arcu arcu, id aliquet ligula fringilla ut. Nunc porta justo sit amet sem commodo, et consequat ipsum euismod. Cras at lacinia nunc. Maecenas sagittis sapien at massa fermentum, eget lacinia mauris laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sagittis est lacus, vel lacinia mauris ultricies non. In ac condimentum sapien, quis ullamcorper justo.</p>
         </div>
  );
}